services:
  postgres:
    image: postgres:16
    restart: "no"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wow
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: